Fix installing yarn

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -21,6 +21,39 @@ semver_range=$(cat $build_dir/package.json | $bp_dir/vendor/jq -r .engines.node)
 npm_semver_range=$(cat $build_dir/package.json | $bp_dir/vendor/jq -r .engines.npm)
 yarn_semver_range=$(cat $build_dir/package.json | $bp_dir/vendor/jq -r .engines.yarn)
 
+get_os() {
+  uname | tr '[:upper:]' '[:lower:]'
+}
+
+RESOLVE="$bp_dir/vendor/resolve-version-$(get_os)"
+
+resolve() {
+  local binary="$1"
+  local versionRequirement="$2"
+  local n=0
+  local output
+
+  # retry this up to 5 times in case of spurious failed API requests
+  until [ $n -ge 5 ]
+  do
+    if output=$($RESOLVE "$binary" "$versionRequirement"); then
+      echo "$output"
+      return 0
+    # don't retry if we get a negative result
+    elif [[ $output = "No result" ]]; then
+      return 1
+    elif [[ $output == "Could not parse"* ]] || [[ $output == "Could not get"* ]]; then
+      return 1
+    else
+      n=$((n+1))
+      # break for a second with a linear backoff
+      sleep $((n+1))
+    fi
+  done
+
+  return 1
+}
+
 set +e
 test ! -z "$yarn_semver_range" -a "$yarn_semver_range" != "null"
 use_yarn=$?
@@ -80,10 +113,18 @@ fi
 
 if [ $use_yarn -eq 0 ]; then
   # Resolve Yarn version using semver.io
-  yarn_version=$(curl --silent --get --data-urlencode "range=${yarn_semver_range}" https://semver.io/yarn/resolve)
-  status "Requested Yarn range:  $yarn_semver_range"
-  status "Resolved Yarn version: $yarn_version"
-  yarn_url="https://yarnpkg.com/downloads/$yarn_version/yarn-v$yarn_version.tar.gz"
+  # yarn_version=$(curl --silent --get --data-urlencode "range=${yarn_semver_range}" https://semver.io/yarn/resolve)
+  # status "Requested Yarn range:  $yarn_semver_range"
+  # status "Resolved Yarn version: $yarn_version"
+
+  echo "Resolving yarn version $yarn_semver_range..."
+  resolve_result=$(resolve yarn "$yarn_semver_range" || echo "failed")
+
+  read -r yarn_version yarn_url < <(echo "$resolve_result")
+
+  echo "Downloading and installing yarn ($yarn_version) ($url) ($resolve_result)..."
+  # yarn_url="https://yarnpkg.com/downloads/$yarn_version/yarn-v$yarn_version.tar.gz"
+  
   mkdir -p $build_dir/vendor/yarn
   curl $yarn_url -s -L -o - | tar xzf - -C $build_dir/vendor/yarn
   export PATH=$build_dir/vendor/yarn/yarn-v$yarn_version/bin:$PATH
